### ISSUE TITLE
It looks like Mongo isn't installing right on GH Actions

### ISSUE THREAD

**Issue by helloworld12321** [UMM-CSci-3601/3601-lab4-mongo-2020#174]
See https://github.com/UMM-CSci-3601/3601-lab4-mongo/runs/1811422327; We're getting the following errors when we try to start the MongoDB service.

```
Unpacking mongo-tools (3.6.3-0ubuntu1) ...
dpkg: error processing archive /var/cache/apt/archives/mongo-tools_3.6.3-0ubuntu1_amd64.deb (--unpack):
 trying to overwrite '/usr/bin/bsondump', which is also in package mongodb-database-tools 100.3.0-1-g8b223b0a
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/mongo-tools_3.6.3-0ubuntu1_amd64.deb
```

I found two other pages on the internet that mention this issue. Neither is particularly helpful. 🙃
https://bugs.launchpad.net/ubuntu/+source/mongo-tools/+bug/1898830
https://bugs.launchpad.net/ubuntu/+source/mongo-tools/+bug/1895001

I wonder if upgrading to a more recent version of Mongo would help? Our workflow is configured to install 3.6, which is a bit old. (I don't know—I'm just speculating! ¯\\\_(ツ)\_/¯) https://docs.mongodb.com/manual/release-notes/

**Comment by helloworld12321** [comment]
UMM-CSci-3601/3601-iteration-template doesn't look like it's exhibiting this problem. Interestingly, its `e2e.yaml` file is slightly different than ours.

lab 4:
```
    services:
      mongo:
        image: mongo:3.4.23
        ports:
          - '27017-27019:27017-27019'
```

iteration template:
```yaml
    services:
      mongo:
        image: mongo
        ports:
          - '27017-27019:27017-27019'
```
